Pulpy\CoreBundle\Entity\HierarchicalConfig:
    type: entity
    table: ~
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

        name:
            type: string
            length: 255
            nullable: false

        config:
            type: json_array

    lifecycleCallbacks: {  }
