### PLATFORM: PAAS

services:

    config.loader.dbbacked:
        class: Pulpy\CoreBundle\Services\Config\Loader\DbBackedConfigLoaderService
        arguments:
            - @doctrine.orm.entity_manager
            - { data.dir: '' }

    config.site:
        class: Pulpy\CoreBundle\Services\Config\SiteConfigService
        arguments:
            - @=service('config.loader.dbbacked').load('config.site')

    fs.persistent:
        class: Pulpy\CoreBundle\Services\PersistentStorage\S3PersistentStorageService
        arguments:
            - @=service('environment').getEnv('S3_BUCKET')
            - @=service('environment').getEnv('S3_KEYID')
            - @=service('environment').getEnv('S3_SECRET')
            - @=service('environment').getScheme() ~ '://' ~ service('environment').getEnv('S3_BUCKET') ~ '.s3.amazonaws.com'

    post.cachehandler:
        class: Pulpy\CoreBundle\Services\CacheHandler\EventedPostCacheHandlerService
        arguments:
            - @fs.persistent
            - @system.status
            - @postfile.repository
            - @post.repository
            - @postfile.topostconverter
            - @doctrine.orm.entity_manager
            - @=service('config.site').getPostsDir()
            - @culture