_init_welcome:
    pattern: _init/welcome
    defaults: { _controller: initialization.controller:welcomeAction }

_init_step1_createdb:
    pattern: _init/step1/db
    defaults: { _controller: initialization.controller:step1CreateDbAction }
    methods: [GET, POST]

_init_step1_createschema:
    pattern: _init/step1/createschema
    defaults: { _controller: initialization.controller:step1CreateSchemaAction }
    methods: [GET, POST]

_init_step1_updateschema:
    pattern: _init/step1/updateschema
    defaults: { _controller: initialization.controller:step1UpdateSchemaAction }
    methods: [GET, POST]

_init_step2:
    pattern: _init/step2
    defaults: { _controller: initialization.controller:step2Action }
    methods: [GET, POST]

_init_finish:
    pattern: _init/finish
    defaults: { _controller: initialization.controller:finishAction }

home:
    pattern: /
    defaults: { _controller: home.controller:indexAction }

# Home page with page > 1
home_paged:
    pattern: /page/{page}
    defaults: { _controller: home.controller:indexAction }
    requirements:
        page: '[2-9]|[0-9]{2,}'

rss:
    pattern: /rss
    defaults: { _controller: feed.controller:indexAction }

json.posts:
    pattern: /json/posts
    defaults: { _controller: json.controller:indexAction }

json.post:
    pattern: /json/posts/{slug}
    defaults: { _controller: json.controller:postAction }
    requirements:
        slug: .+

post:
    pattern: /post/{slug}
    defaults: { _controller: post.controller:indexAction }
    requirements:
        slug: .+
        slug: '^((?!_profiler).)*$'