imports:
    - { resource: defaults/parameters.application.defaults.yml }
    - { resource: defaults/environment.application.defaults.yml }
    - { resource: ../../data/config/parameters.yml, prefix: parameters: }
    - { resource: ../../data/config/environment.defaults.yml }
    - { resource: preprocessors/environment_resolver.php }
    - { resource: preprocessors/database_loader.php }
    - { resource: security.yml }

    - { resource: "@PulpyAdminBundle/Resources/config/config.yml" }
    - { resource: "@PulpyRestBundle/Resources/config/config.yml" }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        #resource: "%kernel.root_dir%/config/preprocessors/routing.php"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    paths:
        "%kernel.root_dir%/../src/Pulpy/CoreBundle/Resources/views": PulpyCore
        "%kernel.root_dir%/../vendor/%theme%/views": PulpyTheme

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    filters:
        cssrewrite: ~
        lessphp: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        path:     "%database_path%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

jms_serializer:
    metadata:
        directories:
            PulpyCore:
                path: "@PulpyCoreBundle/Resources/config/serializer"