security:
    encoders:
        Pulpy\CoreBundle\Entity\AppUser:
            algorithm: sha512
            encode_as_base64: false
            iterations: 1024

    providers:
        appuser:
            entity: { class: Pulpy\CoreBundle\Entity\AppUser, property: email }

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin_login:
            pattern: ^/admin/login
            anonymous: true

        admin:
            pattern: ^/admin
            
            form_login:
                login_path: /admin/login
                check_path: /admin/authcheck
            
            logout:
                path: /admin/logout
                target: /admin