security:
    encoders:
        Pulpy\CoreBundle\Entity\AppUser:
            algorithm: sha512
            encode_as_base64: false
            iterations: 1024

    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
