security:
    encoders:
        Pulpy\CoreBundle\Entity\AppUser:
            algorithm: sha512
            encode_as_base64: false
            iterations: 1024

    providers:
        appuser:
            entity: { class: Pulpy\CoreBundle\Entity\AppUser, property: email }

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            anonymous: true
            context: primary_auth

        admin_login:
            pattern: ^/admin/login
            anonymous: true

        admin:
            pattern: ^/admin
            context: primary_auth
            
            form_login:
                login_path: /admin/login
                check_path: /admin/authcheck
            
            logout:
                path: /admin/logout
                target: /admin


    access_control:
        #- { path: ^/api/posts/?$, access: "hasRole('ROLE_ADMIN')", methods: [GET] }
        #- { path: ^/api/posts/.+$, access: "#post", methods: [GET] }
        - { path: ^/api/.*$, roles: IS_AUTHENTICATED_ANONYMOUSLY }