services:

    pulpy.restbundle.autoroute:
        class: Netgusto\AutorouteBundle\Routing\AutorouteProvider
        arguments:
            resource: "%srcdir%/Pulpy/RestBundle/Resources/config/routing.yml"
        tags:
            - { name: autoroute.provider, prefix: /api }

    rest.posts.controller:
        class: Pulpy\RestBundle\Controller\PostsController